version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

    # optional but nice: group everything into a single PR
    groups:
      python-deps:
        patterns:
          - "*"
